#############################################################################
# Makefile for building: metric-tree
# Generated by qmake (2.01a) (Qt 4.6.2) on: Wed Aug 31 17:04:40 2016
# Project:  metric-tree.pro
# Template: app CONFIG += console network
# Command: /usr/bin/qmake-qt4 -unix -o Makefile metric-tree.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I../../../../lib64/qt4/mkspecs/linux-g++-64 -I. -I../../../include
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   -L/usr/local/lib/ -lboost_system -lboost_thread -lboost_exception -lboost_date_time -lboost_serialization /usr/local/lib/libboost_log_setup.a /usr/local/lib/libboost_log.a /usr/local/lib/libboost_filesystem.a -std=c++0x -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		tcp_session.cpp \
		log.cpp 
OBJECTS       = main.o \
		tcp_session.o \
		log.o
DIST          = ../../../../lib64/qt4/mkspecs/common/g++-multilib.conf \
		../../../../lib64/qt4/mkspecs/common/unix.conf \
		../../../../lib64/qt4/mkspecs/common/linux.conf \
		../../../../lib64/qt4/mkspecs/qconfig.pri \
		../../../../lib64/qt4/mkspecs/features/qt_functions.prf \
		../../../../lib64/qt4/mkspecs/features/qt_config.prf \
		../../../../lib64/qt4/mkspecs/features/exclusive_builds.prf \
		../../../../lib64/qt4/mkspecs/features/default_pre.prf \
		../../../../lib64/qt4/mkspecs/features/release.prf \
		../../../../lib64/qt4/mkspecs/features/default_post.prf \
		../../../../lib64/qt4/mkspecs/features/unix/thread.prf \
		../../../../lib64/qt4/mkspecs/features/warn_on.prf \
		../../../../lib64/qt4/mkspecs/features/resources.prf \
		../../../../lib64/qt4/mkspecs/features/uic.prf \
		../../../../lib64/qt4/mkspecs/features/yacc.prf \
		../../../../lib64/qt4/mkspecs/features/lex.prf \
		../../../../lib64/qt4/mkspecs/features/include_source_dir.prf \
		metric-tree.pro
QMAKE_TARGET  = metric-tree
DESTDIR       = 
TARGET        = metric-tree

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: metric-tree.pro  ../../../../lib64/qt4/mkspecs/linux-g++-64/qmake.conf ../../../../lib64/qt4/mkspecs/common/g++-multilib.conf \
		../../../../lib64/qt4/mkspecs/common/unix.conf \
		../../../../lib64/qt4/mkspecs/common/linux.conf \
		../../../../lib64/qt4/mkspecs/qconfig.pri \
		../../../../lib64/qt4/mkspecs/features/qt_functions.prf \
		../../../../lib64/qt4/mkspecs/features/qt_config.prf \
		../../../../lib64/qt4/mkspecs/features/exclusive_builds.prf \
		../../../../lib64/qt4/mkspecs/features/default_pre.prf \
		../../../../lib64/qt4/mkspecs/features/release.prf \
		../../../../lib64/qt4/mkspecs/features/default_post.prf \
		../../../../lib64/qt4/mkspecs/features/unix/thread.prf \
		../../../../lib64/qt4/mkspecs/features/warn_on.prf \
		../../../../lib64/qt4/mkspecs/features/resources.prf \
		../../../../lib64/qt4/mkspecs/features/uic.prf \
		../../../../lib64/qt4/mkspecs/features/yacc.prf \
		../../../../lib64/qt4/mkspecs/features/lex.prf \
		../../../../lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile metric-tree.pro
../../../../lib64/qt4/mkspecs/common/g++-multilib.conf:
../../../../lib64/qt4/mkspecs/common/unix.conf:
../../../../lib64/qt4/mkspecs/common/linux.conf:
../../../../lib64/qt4/mkspecs/qconfig.pri:
../../../../lib64/qt4/mkspecs/features/qt_functions.prf:
../../../../lib64/qt4/mkspecs/features/qt_config.prf:
../../../../lib64/qt4/mkspecs/features/exclusive_builds.prf:
../../../../lib64/qt4/mkspecs/features/default_pre.prf:
../../../../lib64/qt4/mkspecs/features/release.prf:
../../../../lib64/qt4/mkspecs/features/default_post.prf:
../../../../lib64/qt4/mkspecs/features/unix/thread.prf:
../../../../lib64/qt4/mkspecs/features/warn_on.prf:
../../../../lib64/qt4/mkspecs/features/resources.prf:
../../../../lib64/qt4/mkspecs/features/uic.prf:
../../../../lib64/qt4/mkspecs/features/yacc.prf:
../../../../lib64/qt4/mkspecs/features/lex.prf:
../../../../lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile metric-tree.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/metric-tree1.0.0 || $(MKDIR) .tmp/metric-tree1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/metric-tree1.0.0/ && (cd `dirname .tmp/metric-tree1.0.0` && $(TAR) metric-tree1.0.0.tar metric-tree1.0.0 && $(COMPRESS) metric-tree1.0.0.tar) && $(MOVE) `dirname .tmp/metric-tree1.0.0`/metric-tree1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/metric-tree1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp tcp_server.hpp \
		intdef.hpp \
		tcp_session.h \
		tcp_buffer.hpp \
		tcp_handler.h \
		io_service_pool.hpp \
		inc.hpp \
		log.hpp \
		echo_handler.hpp \
		echo_handler_cmd.hpp \
		daemon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

tcp_session.o: tcp_session.cpp log.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcp_session.o tcp_session.cpp

log.o: log.cpp log.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o log.o log.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

